import { Agama } from "./get/Agama";
import { AktivitasKuliahMahasiswa } from "./get/AktivitasKuliahMahasiswa";
import { AktivitasMengajarDosen } from "./get/AktivitasMengajarDosen";
import { BentukPendidikan } from "./get/BentukPendidikan";
import { BiodataMahasiswa } from "./get/BiodataMahasiswa";
import { CountAktivitasMahasiswa } from "./get/CountAktivitasMahasiswa";
import { CountAktivitasMengajarDosen } from "./get/CountAktivitasMengajarDosen";
import { CountDosen } from "./get/CountDosen";
import { CountDosenPembimbing } from "./get/CountDosenPembimbing";
import { CountDosenPengajarKelasKuliah } from "./get/CountDosenPengajarKelasKuliah";
import { CountKelasKuliah } from "./get/CountKelasKuliah";
import { CountKurikulum } from "./get/CountKurikulum";
import { CountMahasiswa } from "./get/CountMahasiswa";
import { CountMahasiswaBimbinganDosen } from "./get/CountMahasiswaBimbinganDosen";
import { CountMahasiswaLulusDO } from "./get/CountMahasiswaLulusDO";
import { CountMataKuliah } from "./get/CountMataKuliah";
import { CountMatkulKurikulum } from "./get/CountMatkulKurikulum";
import { CountNilaiPerkuliahanKelas } from "./get/CountNilaiPerkuliahanKelas";
import { CountNilaiTransferPendidikanMahasiswa } from "./get/CountNilaiTransferPendidikanMahasiswa";
import { CountPenugasanSemuaDosen } from "./get/CountPenugasanSemuaDosen";
import { CountPerguruanTinggi } from "./get/CountPerguruanTinggi";
import { CountPeriodePerkuliahan } from "./get/CountPeriodePerkuliahan";
import { CountPerkuliahanMahasiswa } from "./get/CountPerkuliahanMahasiswa";
import { CountPesertaKelasKuliah } from "./get/CountPesertaKelasKuliah";
import { CountPrestasiMahasiswa } from "./get/CountPrestasiMahasiswa";
import { CountProdi } from "./get/CountProdi";
import { CountRiwayatNilaiMahasiswa } from "./get/CountRiwayatNilaiMahasiswa";
import { CountRiwayatPendidikanMahasiswa } from "./get/CountRiwayatPendidikanMahasiswa";
import { CountSkalaNilaiProdi } from "./get/CountSkalaNilaiProdi";
import { CountSubstansiKuliah } from "./get/CountSubstansiKuliah";
import { DataLengkapMahasiswaProdi } from "./get/DataLengkapMahasiswaProdi";
import { DetailBiodataDosen } from "./get/DetailBiodataDosen";
import { DetailKelasKuliah } from "./get/DetailKelasKuliah";
import { DetailKurikulum } from "./get/DetailKurikulum";
import { DetailMahasiswaLulusDO } from "./get/DetailMahasiswaLulusDO";
import { DetailMataKuliah } from "./get/DetailMataKuliah";
import { DetailNilaiPerkuliahanKelas } from "./get/DetailNilaiPerkuliahanKelas";
import { DetailPerkuliahanMahasiswa } from "./get/DetailPerkuliahanMahasiswa";
import { DosenPengajarKelasKuliah } from "./get/DosenPengajarKelasKuliah";
import { IkatanKerjaSdm } from "./get/IkatanKerjaSdm";
import { Jabfung } from "./get/Jabfung";
import { JalurMasuk } from "./get/JalurMasuk";
import { JenisAktivitasMahasiswa } from "./get/JenisAktivitasMahasiswa";
import { JenisEvaluasi } from "./get/JenisEvaluasi";
import { JenisKeluar } from "./get/JenisKeluar";
import { JenisPendaftaran } from "./get/JenisPendaftaran";
import { JenisPrestasi } from "./get/JenisPrestasi";
import { JenisSertifikasi } from "./get/JenisSertifikasi";
import { JenisSMS } from "./get/JenisSMS";
import { JenisSubstansi } from "./get/JenisSubstansi";
import { JenisTinggal } from "./get/JenisTinggal";
import { JenjangPendidikan } from "./get/JenjangPendidikan";
import { KategoriKegiatan } from "./get/KategoriKegiatan";
import { KebutuhanKhusus } from "./get/KebutuhanKhusus";
import { KRSMahasiswa } from "./get/KRSMahasiswa";
import { LembagaPengangkat } from "./get/LembagaPengangkat";
import { LevelWilayah } from "./get/LevelWilayah";
import { ListAktivitasMahasiswa } from "./get/ListAktivitasMahasiswa";
import { ListAnggotaAktivitasMahasiswa } from "./get/ListAnggotaAktivitasMahasiswa";
import { ListBimbingMahasiswa } from "./get/ListBimbingMahasiswa";
import { ListDosen } from "./get/ListDosen";
import { ListKelasKuliah } from "./get/ListKelasKuliah";
import { ListKurikulum } from "./get/ListKurikulum";
import { ListMahasiswa } from "./get/ListMahasiswa";
import { ListMataKuliah } from "./get/ListMataKuliah";
import { ListNilaiPerkuliahanKelas } from "./get/ListNilaiPerkuliahanKelas";
import { ListPenugasanDosen } from "./get/ListPenugasanDosen";
import { ListPenugasanSemuaDosen } from "./get/ListPenugasanSemuaDosen";
import { ListPerkuliahanMahasiswa } from "./get/ListPerkuliahanMahasiswa";
import { ListPrestasiMahasiswa } from "./get/ListPrestasiMahasiswa";
import { ListRiwayatPendidikanMahasiswa } from "./get/ListRiwayatPendidikanMahasiswa";
import { ListSubstansiKuliah } from "./get/ListSubstansiKuliah";
import { ListUjiMahasiswa } from "./get/ListUjiMahasiswa";
import { MahasiswaBimbinganDosen } from "./get/MahasiswaBimbinganDosen";
import { MatkulKurikulum } from "./get/MatkulKurikulum";
import { Negara } from "./get/Negara";
import { NilaiTransferPendidikanMahasiswa } from "./get/NilaiTransferPendidikanMahasiswa";
import { PangkatGolongan } from "./get/PangkatGolongan";
import { Pekerjaan } from "./get/Pekerjaan";
import { Pembiayaan } from "./get/Pembiayaan";
import { Penghasilan } from "./get/Penghasilan";
import { PerhitunganSKS } from "./get/PerhitunganSKS";
import { Periode } from "./get/Periode";
import { PesertaKelasKuliah } from "./get/PesertaKelasKuliah";
import { Prodi } from "./get/Prodi";
import { ProfilPT } from "./get/ProfilPT";
import { RiwayatFungsionalDosen } from "./get/RiwayatFungsionalDosen";
import { RiwayatNilaiMahasiswa } from "./get/RiwayatNilaiMahasiswa";
import { RiwayatPangkatDosen } from "./get/RiwayatPangkatDosen";
import { RiwayatPendidikanDosen } from "./get/RiwayatPendidikanDosen";
import { RiwayatPenelitianDosen } from "./get/RiwayatPenelitianDosen";
import { RiwayatSertifikasiDosen } from "./get/RiwayatSertifikasiDosen";
import { Semester } from "./get/Semester";
import { StatusKeaktifanPegawai } from "./get/StatusKeaktifanPegawai";
import { StatusKepegawaian } from "./get/StatusKepegawaian";
import { StatusMahasiswa } from "./get/StatusMahasiswa";
import { TahunAjaran } from "./get/TahunAjaran";
import { TingkatPrestasi } from "./get/TingkatPrestasi";
import { TranskripMahasiswa } from "./get/TranskripMahasiswa";
import { Wilayah } from "./get/Wilayah";
import { AlatTransportasi } from "./get/AlatTransportasi";

export type GetResponse = {
  Agama: Agama;
  AktivitasKuliahMahasiswa: AktivitasKuliahMahasiswa;
  AktivitasMengajarDosen: AktivitasMengajarDosen;
  BentukPendidikan: BentukPendidikan;
  BiodataMahasiswa: BiodataMahasiswa;
  CountAktivitasMahasiswa: CountAktivitasMahasiswa;
  CountAktivitasMengajarDosen: CountAktivitasMengajarDosen;
  CountDosen: CountDosen;
  CountDosenPembimbing: CountDosenPembimbing;
  CountDosenPengajarKelasKuliah: CountDosenPengajarKelasKuliah;
  CountKelasKuliah: CountKelasKuliah;
  CountKurikulum: CountKurikulum;
  CountMahasiswa: CountMahasiswa;
  CountMahasiswaBimbinganDosen: CountMahasiswaBimbinganDosen;
  CountMahasiswaLulusDO: CountMahasiswaLulusDO;
  CountMataKuliah: CountMataKuliah;
  CountMatkulKurikulum: CountMatkulKurikulum;
  CountNilaiPerkuliahanKelas: CountNilaiPerkuliahanKelas;
  CountNilaiTransferPendidikanMahasiswa: CountNilaiTransferPendidikanMahasiswa;
  CountPenugasanSemuaDosen: CountPenugasanSemuaDosen;
  CountPerguruanTinggi: CountPerguruanTinggi;
  CountPeriodePerkuliahan: CountPeriodePerkuliahan;
  CountPerkuliahanMahasiswa: CountPerkuliahanMahasiswa;
  CountPesertaKelasKuliah: CountPesertaKelasKuliah;
  CountPrestasiMahasiswa: CountPrestasiMahasiswa;
  CountProdi: CountProdi;
  CountRiwayatNilaiMahasiswa: CountRiwayatNilaiMahasiswa;
  CountRiwayatPendidikanMahasiswa: CountRiwayatPendidikanMahasiswa;
  CountSkalaNilaiProdi: CountSkalaNilaiProdi;
  CountSubstansiKuliah: CountSubstansiKuliah;
  DataLengkapMahasiswaProdi: DataLengkapMahasiswaProdi;
  DetailBiodataDosen: DetailBiodataDosen;
  DetailKelasKuliah: DetailKelasKuliah;
  DetailKurikulum: DetailKurikulum;
  DetailMahasiswaLulusDO: DetailMahasiswaLulusDO;
  DetailMataKuliah: DetailMataKuliah;
  DetailNilaiPerkuliahanKelas: DetailNilaiPerkuliahanKelas;
  DetailPerkuliahanMahasiswa: DetailPerkuliahanMahasiswa;
  DosenPengajarKelasKuliah: DosenPengajarKelasKuliah;
  IkatanKerjaSdm: IkatanKerjaSdm;
  Jabfung: Jabfung;
  JalurMasuk: JalurMasuk;
  JenisAktivitasMahasiswa: JenisAktivitasMahasiswa;
  JenisEvaluasi: JenisEvaluasi;
  JenisKeluar: JenisKeluar;
  JenisPendaftaran: JenisPendaftaran;
  JenisPrestasi: JenisPrestasi;
  JenisSertifikasi: JenisSertifikasi;
  JenisSMS: JenisSMS;
  JenisSubstansi: JenisSubstansi;
  JenisTinggal: JenisTinggal;
  JenjangPendidikan: JenjangPendidikan;
  KategoriKegiatan: KategoriKegiatan;
  KebutuhanKhusus: KebutuhanKhusus;
  KRSMahasiswa: KRSMahasiswa;
  LembagaPengangkat: LembagaPengangkat;
  LevelWilayah: LevelWilayah;
  ListAktivitasMahasiswa: ListAktivitasMahasiswa;
  ListAnggotaAktivitasMahasiswa: ListAnggotaAktivitasMahasiswa;
  ListBimbingMahasiswa: ListBimbingMahasiswa;
  ListDosen: ListDosen;
  ListKelasKuliah: ListKelasKuliah;
  ListKurikulum: ListKurikulum;
  ListMahasiswa: ListMahasiswa;
  ListMataKuliah: ListMataKuliah;
  ListNilaiPerkuliahanKelas: ListNilaiPerkuliahanKelas;
  ListPenugasanDosen: ListPenugasanDosen;
  ListPenugasanSemuaDosen: ListPenugasanSemuaDosen;
  ListPerkuliahanMahasiswa: ListPerkuliahanMahasiswa;
  ListPrestasiMahasiswa: ListPrestasiMahasiswa;
  ListRiwayatPendidikanMahasiswa: ListRiwayatPendidikanMahasiswa;
  ListSubstansiKuliah: ListSubstansiKuliah;
  ListUjiMahasiswa: ListUjiMahasiswa;
  MahasiswaBimbinganDosen: MahasiswaBimbinganDosen;
  MatkulKurikulum: MatkulKurikulum;
  Negara: Negara;
  NilaiTransferPendidikanMahasiswa: NilaiTransferPendidikanMahasiswa;
  PangkatGolongan: PangkatGolongan;
  Pekerjaan: Pekerjaan;
  Pembiayaan: Pembiayaan;
  Penghasilan: Penghasilan;
  PerhitunganSKS: PerhitunganSKS;
  Periode: Periode;
  PesertaKelasKuliah: PesertaKelasKuliah;
  Prodi: Prodi;
  ProfilPT: ProfilPT;
  RiwayatFungsionalDosen: RiwayatFungsionalDosen;
  RiwayatNilaiMahasiswa: RiwayatNilaiMahasiswa;
  RiwayatPangkatDosen: RiwayatPangkatDosen;
  RiwayatPendidikanDosen: RiwayatPendidikanDosen;
  RiwayatPenelitianDosen: RiwayatPenelitianDosen;
  RiwayatSertifikasiDosen: RiwayatSertifikasiDosen;
  Semester: Semester;
  StatusKeaktifanPegawai: StatusKeaktifanPegawai;
  StatusKepegawaian: StatusKepegawaian;
  StatusMahasiswa: StatusMahasiswa;
  TahunAjaran: TahunAjaran;
  TingkatPrestasi: TingkatPrestasi;
  TranskripMahasiswa: TranskripMahasiswa;
  Wilayah: Wilayah;
  AlatTransportasi: AlatTransportasi;
};
