export const InsertActions: { [key: string]: string } = {
  AktivitasMahasiswa: "InsertAktivitasMahasiswa",
  AnggotaAktivitasMahasiswa: "InsertAnggotaAktivitasMahasiswa",
  BimbingMahasiswa: "InsertBimbingMahasiswa",
  BiodataMahasiswa: "InsertBiodataMahasiswa",
  DosenPengajarKelasKuliah: "InsertDosenPengajarKelasKuliah",
  KelasKuliah: "InsertKelasKuliah",
  Kurikulum: "InsertKurikulum",
  MataKuliah: "InsertMataKuliah",
  MatkulKurikulum: "InsertMatkulKurikulum",
  NilaiTransferPendidikanMahasiswa: "InsertNilaiTransferPendidikanMahasiswa",
  PeriodePerkuliahan: "InsertPeriodePerkuliahan",
  PerkuliahanMahasiswa: "InsertPerkuliahanMahasiswa",
  PesertaKelasKuliah: "InsertPesertaKelasKuliah",
  PrestasiMahasiswa: "InsertPrestasiMahasiswa",
  RiwayatPendidikanMahasiswa: "InsertRiwayatPendidikanMahasiswa",
  SubstansiKuliah: "InsertSubstansiKuliah",
  TranskripMahasiswa: "InsertTranskripMahasiswa",
  UjiMahasiswa: "InsertUjiMahasiswa",
  MahasiswaLulusDO: "InsertMahasiswaLulusDO",
  DosenPembimbing: "InsertDosenPembimbing",
  SkalaNilaiProdi: "InsertSkalaNilaiProdi",
  DayaTampungMahasiswa: "InsertDayaTampungMahasiswa",
};
